server:
  port: 9090

spring:
  datasource:
    url: jdbc:h2:mem:mydb;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
    driverClassName: org.h2.Driver

logging:
  level:
    root: INFO
    org.springframework.web: INFO
