server:
  port: 8080

spring:
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:mem:mydb
    username: user
    password: password
    driverClassName: org.h2.Driver
    
logging:
  level:
    root: INFO
    org.springframework.web: INFO